"""Tenfold Gen-2 constitutional implementation.

Gen 2 is built under frozen TF-00 + G2-00 authority. Until G2-27 proves
Self-Construction Minimum, importing this package transfers no live Gen-1
execution authority to Gen 2.
"""

from __future__ import annotations

import importlib
from typing import Any

__all__ = [
    "ArtifactBinding",
    "ComponentDisposition",
    "Disposition",
    "EnvironmentBinding",
    "Gen1DifferentialHarness",
    "Gen1ReferenceBundle",
    "IntentionalDivergence",
    "InterimRootBinding",
    "ReferenceCoverage",
    "ReferenceCoverageClass",
    "ReferenceError",
    "AmbiguityImpactDomain",
    "AmbiguityRecord",
    "AmbiguityState",
    "AssuranceCopySlot",
    "AuthorityTransferRecord",
    "AuthorityTransferStabilizationPolicy",
    "AuthorityTransferStage",
    "CandidateLedger",
    "CandidateLedgerEntry",
    "CandidatePathDisposition",
    "CandidatePolicyLedgerEntry",
    "ChronicleEvent",
    "ClassificationClosure",
    "ClassificationEntry",
    "CompilationCertificate",
    "ConstitutionalCampaignProgram",
    "ConstitutionalError",
    "ConstitutionalPolicySet",
    "EscapeClass",
    "EscapeObservation",
    "ExternalAssuranceBinding",
    "ExternalAssuranceCopy",
    "FalsificationClass",
    "ObligationClass",
    "ObligationIR",
    "ObligationIRNode",
    "POLICY_MUTATION_OPERATOR_SET_GENERATION",
    "PolicyClosureManifest",
    "PolicyMutationExemption",
    "PolicyMutationOperator",
    "ProofGraph",
    "ProofGraphNode",
    "ProofState",
    "QualificationPackage",
    "Requirement",
    "RequirementClass",
    "RequirementClosureManifest",
    "RuntimeObligation",
    "STABILIZATION_EVIDENCE_CATEGORIES",
    "ComponentLineage",
    "ConvergenceStatistics",
    "DisagreementRecord",
    "DisagreementSide",
    "ExternalAssuranceReconciliationResult",
    "LineageKind",
    "SharedTrustSurfaceEntry",
    "SharedTrustSurfaceManifest",
    "SharingClass",
    "UndeclaredCommonModeDependency",
    "VerifierError",
    "VerifierSpecificationDelta",
    "independent_canonical_digest",
    "independent_decode_canonical_json",
    "independent_reconcile_external_assurance",
    "independent_can_emit_authoritative_non_occurrence",
    "independent_check_typed_coverage",
    "independent_compute_proof_verdict",
    "independent_derive_expected_runtime_obligation_set",
    "independent_derive_mandatory_assurance",
    "independent_verify_closed_schema",
    "independent_verify_obligation_ir",
    "independent_verify_requirement_closure_manifest",
    "scan_for_undeclared_common_mode_dependencies",
    "FixtureStatus",
    "MutationCategory",
    "MutationError",
    "MutationFixture",
    "MutationScoreReport",
    "MutationSuite",
    "REQUIRED_MUTATION_CATEGORIES",
    "build_initial_mutation_suite",
    "ClassificationMergeRecord",
    "EscapeRateReport",
    "PathCChallenge",
    "PathCDisposition",
    "RetrospectiveProbeRecord",
    "RetrospectiveProbeRegistry",
    "RetrospectiveProbeStatus",
    "compute_escape_rate_report",
    "enumerate_policy_escape_blast_radius",
    "has_common_cause_risk",
    "merge_classification_entries",
    "reconcile_requirement_closure",
    "record_policy_escape",
    "requires_path_c_challenge",
    "CompiledCampaign",
    "TASK_DERIVATION_RULE_REF",
    "TransformationWitness",
    "check_falsification_topology_baseline",
    "compile_campaign_program",
    "compute_constitutional_baseline",
    "compute_predecessor_depth",
    "reconcile_compiled_campaign",
    "AssignmentGeneration",
    "AuthorityGeneration",
    "CampaignIdentity",
    "IdentityGenerationError",
    "OrganizationGeneration",
    "check_generation_not_stale",
    "gen1_check_exact_state_binding",
    "organization_generation_from_interim_root",
    "reinstate_under_fresh_generation",
    "AuthorityHolder",
    "FailureSpaceCoverageReport",
    "FailureSpaceDimension",
    "G2_09_REQUIRED_STATE_MODEL_FIELD_IDS",
    "G2_10_REQUIRED_STATE_MODEL_FIELD_IDS",
    "StateModel",
    "StateModelDisposition",
    "StateModelError",
    "StateModelField",
    "build_g2_09_base_state_model",
    "build_g2_10_state_model",
    "check_standing_gate_d",
    "generate_one_wise",
    "generate_pairwise",
    "ChronicleCliBuildError",
    "ChronicleCliError",
    "append_entry",
    "check_checkpoint",
    "check_tail_loss",
    "dump_as_chronicle_events",
    "open_chronicle",
    "G2_11_REQUIRED_STATE_MODEL_FIELD_IDS",
    "build_g2_11_state_model",
    "gen1_check_mutation_admission",
    "gen1_compute_frontier",
    "gen1_lease_acquire",
    "gen1_lease_fence",
    "gen1_lease_validate_token",
    "sealed_task_dispatch_digest",
    "DispatchLeaseCliBuildError",
    "DispatchLeaseCliError",
    "rust_check_mutation_admission",
    "rust_compute_frontier",
    "rust_lease_acquire",
    "rust_lease_fence",
    "rust_lease_validate_token",
    "rust_restore_check",
    "G2_12_REQUIRED_STATE_MODEL_FIELD_IDS",
    "build_g2_12_state_model",
    "HermeticProofRecord",
    "admit_evidence",
    "compute_proof_verdict",
    "derive_mandatory_assurance",
    "verify_fresh_hermetic_proof",
    "ProofGraphCliBuildError",
    "ProofGraphCliError",
    "rust_admit_evidence",
    "rust_check_falsification_topology_baseline",
    "rust_compute_proof_verdict",
    "rust_derive_mandatory_assurance",
    "rust_verify_fresh_hermetic_proof",
    "AssuranceBindingClaim",
    "G2_13_REQUIRED_STATE_MODEL_FIELD_IDS",
    "build_g2_13_state_model",
    "independent_derive_expected_runtime_obligation_set",
    "ExpectedRuntimeObligation",
    "HazardDisposition",
    "HazardRecord",
    "InvariantCandidateDisposition",
    "InvariantCandidateEntry",
    "InvariantCandidateLedger",
    "InvariantSource",
    "Observer",
    "ObserverFinding",
    "ObserverCoverageDomain",
    "IMPLEMENTED_OBSERVER_COVERAGE_DOMAINS",
    "DEFERRED_OBSERVER_COVERAGE_DOMAINS",
    "RuntimeObligationCandidateDisposition",
    "RuntimeObligationCandidateEntry",
    "RuntimeObligationCandidateLedger",
    "RuntimeObligationClassDeclaration",
    "RuntimeObligationClassKind",
    "RuntimeObligationError",
    "RuntimeObligationRegistry",
    "TerminalDisposition",
    "UnresolvedEffectObservation",
    "check_hazard_disposition_resolves",
    "check_observer_coverage_roster_is_fully_accounted_for",
    "check_observer_has_no_mutation_authority",
    "derive_expected_runtime_obligations",
    "find_missing_runtime_obligations",
    "has_intent_implementation_agreement",
    "RuntimeObligationCliBuildError",
    "RuntimeObligationCliError",
    "rust_check_hazard_record",
    "rust_derive_expected_runtime_obligations",
    "rust_find_missing_runtime_obligations",
    "G2_14_REQUIRED_STATE_MODEL_FIELD_IDS",
    "build_g2_14_state_model",
    "G2_15_REQUIRED_STATE_MODEL_FIELD_IDS",
    "build_g2_15_state_model",
    "FacilityAdapterBoundary",
    "FacilityContract",
    "FacilityError",
    "FacilityIOClass",
    "FacilityProperty",
    "FacilityPropertyQualificationHarness",
    "LocalSandboxFacility",
    "PropertyQualificationRecord",
    "QualificationState",
    "RealMutatingFacilityAuthorityDisabled",
    "SandboxScenarioResult",
    "StaleGenerationRejected",
    "check_critical_gate",
    "gen1_check_read_only_facility_admission",
    "gen1_wrap_read_only_facility_task",
    "FacilityCliBuildError",
    "FacilityCliError",
    "rust_can_emit_authoritative_non_occurrence",
    "rust_validate_facility_contract",
    "AmbientAuthorityInventory",
    "ExecutionAuthorityState",
    "ExecutionContextError",
    "ExecutionContextPrincipal",
    "ExecutionImageLineage",
    "HighRiskUnboundedExecutionRejected",
    "ProbeResult",
    "ProbeStatus",
    "UnadmittedAuthorityReachable",
    "check_high_risk_execution_admission",
    "check_no_unadmitted_authority",
    "classify_execution_authority_state",
    "compute_p0",
    "probe_held_authority",
    "probe_local_positional_authority",
    "probe_network_positional_authority",
    "AutomationCrossCheckResult",
    "CapabilityCausationGraph",
    "CapabilityGraphError",
    "CapabilityNode",
    "CausalEdge",
    "ContainingScopeTraversalResult",
    "EffectivePolicyClaim",
    "EffectReachResult",
    "EnumerationState",
    "HighRiskUnboundedReachRejected",
    "KnownCausalEdgeClass",
    "LocalAutomationSubstrate",
    "NodeKind",
    "ObservationCover",
    "ObservationCoverGapDetected",
    "PositiveControlAttachment",
    "ReachState",
    "SubstrateCapabilityGeneration",
    "SubstrateCapabilityGenerationStale",
    "check_high_risk_reach_admission",
    "check_high_risk_reach_state_admission",
    "check_observation_cover_containment",
    "check_substrate_capability_generation_current",
    "classify_reach_state",
    "compute_effect_reach_star",
    "cross_check_effective_policy",
    "query_effective_policy",
    "traverse_containing_scope",
    "verify_positive_control_detected",
    "CapabilityGraphCliBuildError",
    "CapabilityGraphCliError",
    "rust_check_high_risk_reach_admission",
    "rust_check_observation_cover_containment",
    "rust_compute_effect_reach_star",
    "rust_cross_check_effective_policy",
    "AuthorityChain",
    "AuthorityPlane",
    "CausalPreimageResult",
    "CreatedPrincipalAuthorityQuery",
    "LocalPrincipalAuthoritySubstrate",
    "MintableScopeBound",
    "PlaneRole",
    "RootAmendment",
    "RootAuthorityError",
    "check_control_plane_exclusion",
    "check_created_principal_within_mintable_bound",
    "check_successor_bound_non_expansion",
    "compute_causal_preimage_star",
    "query_created_principal_authority",
    "RootAuthorityCliBuildError",
    "RootAuthorityCliError",
    "rust_check_control_plane_exclusion",
    "rust_check_created_principal_within_mintable_bound",
    "rust_check_successor_bound_non_expansion",
    "rust_compute_causal_preimage_star",
    "ALL_MANDATORY_CENSUS_BOUNDARIES",
    "CensusBoundary",
    "EffectCensusEntry",
    "EffectCensusError",
    "EffectCensusRecord",
    "EffectCensusResidueClass",
    "EffectIssuanceBarrier",
    "EffectIssuanceState",
    "ExpectedEffect",
    "LatencyBounds",
    "ObservationCoverStateDigest",
    "ObservedEffect",
    "ObservedLatencies",
    "TerminalEffectSignal",
    "check_effect_integrity",
    "check_latency_bounds",
    "check_mandatory_census_boundaries_covered",
    "check_no_blind_replay",
    "check_no_new_intent_after_closure",
    "check_observation_cover_recheck",
    "classify_effect_census",
    "classify_terminal_signal",
    "close_effect_issuance",
    "compute_observation_cover_state_digest",
    "reopen_effect_issuance",
    "EffectCensusCliBuildError",
    "EffectCensusCliError",
    "rust_check_effect_integrity",
    "rust_check_latency_bounds",
    "rust_check_mandatory_census_boundaries_covered",
    "rust_check_no_blind_replay",
    "rust_check_no_new_intent_after_closure",
    "rust_check_observation_cover_recheck",
    "rust_close_effect_issuance",
    "rust_reopen_effect_issuance",
    "PROTOCOL_VERSION",
    "BootstrapProtocolError",
    "EvidencePacketV1",
    "FacilityRequestV1",
    "FacilityResultV1",
    "RuntimeIdentity",
    "RuntimeKind",
    "TaskPacketV1",
    "check_evidence_packet_generation_current",
    "check_facility_result_matches_request",
    "validate_bootstrap_corpus",
    "verify_chronicle_entry_self_digest",
    "BootstrapProtocolCliBuildError",
    "BootstrapProtocolCliError",
    "rust_check_evidence_packet_generation_current",
    "rust_check_facility_result_matches_request",
    "rust_validate_bootstrap_corpus",
    "rust_validate_task_packet",
]

# PEP 562 lazy exports: mechanically derived from this package's own
# former eager `from .module import (...)` statements -- a 1:1
# transcription, not a re-derivation. Importing this package no longer
# eagerly imports every submodule (several of which, e.g. dispatch_lease,
# genuinely and intentionally import tenfold.foreman/tenfold.ownership/
# tenfold.facility as real Gen1 differential-testing oracles for their
# own purposes) -- each submodule now loads only on first genuine access
# to one of its names, exactly like `from tenfold.gen2 import X` /
# `tenfold.gen2.X` always behaved from the caller's point of view.
_LAZY_EXPORTS: dict[str, str] = {
    "ArtifactBinding": "reference",
    "ComponentDisposition": "reference",
    "Disposition": "reference",
    "EnvironmentBinding": "reference",
    "Gen1DifferentialHarness": "reference",
    "Gen1ReferenceBundle": "reference",
    "IntentionalDivergence": "reference",
    "InterimRootBinding": "reference",
    "ReferenceCoverage": "reference",
    "ReferenceCoverageClass": "reference",
    "ReferenceError": "reference",
    "AmbiguityImpactDomain": "constitutional",
    "AmbiguityRecord": "constitutional",
    "AmbiguityState": "constitutional",
    "AssuranceCopySlot": "constitutional",
    "AuthorityTransferRecord": "constitutional",
    "AuthorityTransferStabilizationPolicy": "constitutional",
    "AuthorityTransferStage": "constitutional",
    "CandidateLedger": "constitutional",
    "CandidateLedgerEntry": "constitutional",
    "CandidatePathDisposition": "constitutional",
    "CandidatePolicyLedgerEntry": "constitutional",
    "ChronicleEvent": "constitutional",
    "ClassificationClosure": "constitutional",
    "ClassificationEntry": "constitutional",
    "CompilationCertificate": "constitutional",
    "ConstitutionalCampaignProgram": "constitutional",
    "ConstitutionalError": "constitutional",
    "ConstitutionalPolicySet": "constitutional",
    "EscapeClass": "constitutional",
    "EscapeObservation": "constitutional",
    "ExternalAssuranceBinding": "constitutional",
    "ExternalAssuranceCopy": "constitutional",
    "FalsificationClass": "constitutional",
    "ObligationClass": "constitutional",
    "ObligationIR": "constitutional",
    "ObligationIRNode": "constitutional",
    "POLICY_MUTATION_OPERATOR_SET_GENERATION": "constitutional",
    "PolicyClosureManifest": "constitutional",
    "PolicyMutationExemption": "constitutional",
    "PolicyMutationOperator": "constitutional",
    "ProofGraph": "constitutional",
    "ProofGraphNode": "constitutional",
    "ProofState": "constitutional",
    "QualificationPackage": "constitutional",
    "Requirement": "constitutional",
    "RequirementClass": "constitutional",
    "RequirementClosureManifest": "constitutional",
    "RuntimeObligation": "constitutional",
    "STABILIZATION_EVIDENCE_CATEGORIES": "constitutional",
    "ComponentLineage": "verifier",
    "ConvergenceStatistics": "verifier",
    "DisagreementRecord": "verifier",
    "DisagreementSide": "verifier",
    "ExternalAssuranceReconciliationResult": "verifier",
    "LineageKind": "verifier",
    "SharedTrustSurfaceEntry": "verifier",
    "SharedTrustSurfaceManifest": "verifier",
    "SharingClass": "verifier",
    "UndeclaredCommonModeDependency": "verifier",
    "VerifierError": "verifier",
    "VerifierSpecificationDelta": "verifier",
    "independent_canonical_digest": "verifier",
    "independent_decode_canonical_json": "verifier",
    "independent_reconcile_external_assurance": "verifier",
    "independent_can_emit_authoritative_non_occurrence": "verifier",
    "independent_check_typed_coverage": "verifier",
    "independent_compute_proof_verdict": "verifier",
    "independent_derive_expected_runtime_obligation_set": "verifier",
    "independent_derive_mandatory_assurance": "verifier",
    "independent_verify_closed_schema": "verifier",
    "independent_verify_obligation_ir": "verifier",
    "independent_verify_requirement_closure_manifest": "verifier",
    "scan_for_undeclared_common_mode_dependencies": "verifier",
    "FixtureStatus": "mutation_suite",
    "MutationCategory": "mutation_suite",
    "MutationError": "mutation_suite",
    "MutationFixture": "mutation_suite",
    "MutationScoreReport": "mutation_suite",
    "MutationSuite": "mutation_suite",
    "REQUIRED_MUTATION_CATEGORIES": "mutation_suite",
    "build_initial_mutation_suite": "mutation_fixtures",
    "ClassificationMergeRecord": "closure_runtime",
    "EscapeRateReport": "closure_runtime",
    "PathCChallenge": "closure_runtime",
    "PathCDisposition": "closure_runtime",
    "RetrospectiveProbeRecord": "closure_runtime",
    "RetrospectiveProbeRegistry": "closure_runtime",
    "RetrospectiveProbeStatus": "closure_runtime",
    "compute_escape_rate_report": "closure_runtime",
    "enumerate_policy_escape_blast_radius": "closure_runtime",
    "has_common_cause_risk": "closure_runtime",
    "merge_classification_entries": "closure_runtime",
    "reconcile_requirement_closure": "closure_runtime",
    "record_policy_escape": "closure_runtime",
    "requires_path_c_challenge": "closure_runtime",
    "CompiledCampaign": "campaign_compiler",
    "TASK_DERIVATION_RULE_REF": "campaign_compiler",
    "TransformationWitness": "campaign_compiler",
    "check_falsification_topology_baseline": "campaign_compiler",
    "compile_campaign_program": "campaign_compiler",
    "compute_constitutional_baseline": "campaign_compiler",
    "compute_predecessor_depth": "campaign_compiler",
    "reconcile_compiled_campaign": "campaign_compiler",
    "AssignmentGeneration": "identity_generation",
    "AuthorityGeneration": "identity_generation",
    "CampaignIdentity": "identity_generation",
    "IdentityGenerationError": "identity_generation",
    "OrganizationGeneration": "identity_generation",
    "check_generation_not_stale": "identity_generation",
    "gen1_check_exact_state_binding": "identity_generation",
    "organization_generation_from_interim_root": "identity_generation",
    "reinstate_under_fresh_generation": "identity_generation",
    "AuthorityHolder": "state_model",
    "FailureSpaceCoverageReport": "state_model",
    "FailureSpaceDimension": "state_model",
    "G2_09_REQUIRED_STATE_MODEL_FIELD_IDS": "state_model",
    "G2_10_REQUIRED_STATE_MODEL_FIELD_IDS": "state_model",
    "StateModel": "state_model",
    "StateModelDisposition": "state_model",
    "StateModelError": "state_model",
    "StateModelField": "state_model",
    "build_g2_09_base_state_model": "state_model",
    "build_g2_10_state_model": "state_model",
    "check_standing_gate_d": "state_model",
    "generate_one_wise": "state_model",
    "generate_pairwise": "state_model",
    "ChronicleCliBuildError": "chronicle_bridge",
    "ChronicleCliError": "chronicle_bridge",
    "append_entry": "chronicle_bridge",
    "check_checkpoint": "chronicle_bridge",
    "check_tail_loss": "chronicle_bridge",
    "dump_as_chronicle_events": "chronicle_bridge",
    "open_chronicle": "chronicle_bridge",
    "G2_11_REQUIRED_STATE_MODEL_FIELD_IDS": "state_model",
    "build_g2_11_state_model": "state_model",
    "gen1_check_mutation_admission": "dispatch_lease",
    "gen1_compute_frontier": "dispatch_lease",
    "gen1_lease_acquire": "dispatch_lease",
    "gen1_lease_fence": "dispatch_lease",
    "gen1_lease_validate_token": "dispatch_lease",
    "sealed_task_dispatch_digest": "dispatch_lease",
    "DispatchLeaseCliBuildError": "dispatch_lease_bridge",
    "DispatchLeaseCliError": "dispatch_lease_bridge",
    "rust_check_mutation_admission": "dispatch_lease_bridge",
    "rust_compute_frontier": "dispatch_lease_bridge",
    "rust_lease_acquire": "dispatch_lease_bridge",
    "rust_lease_fence": "dispatch_lease_bridge",
    "rust_lease_validate_token": "dispatch_lease_bridge",
    "rust_restore_check": "dispatch_lease_bridge",
    "G2_12_REQUIRED_STATE_MODEL_FIELD_IDS": "state_model",
    "build_g2_12_state_model": "state_model",
    "HermeticProofRecord": "proof_graph",
    "admit_evidence": "proof_graph",
    "compute_proof_verdict": "proof_graph",
    "derive_mandatory_assurance": "proof_graph",
    "verify_fresh_hermetic_proof": "proof_graph",
    "ProofGraphCliBuildError": "proof_graph_bridge",
    "ProofGraphCliError": "proof_graph_bridge",
    "rust_admit_evidence": "proof_graph_bridge",
    "rust_check_falsification_topology_baseline": "proof_graph_bridge",
    "rust_compute_proof_verdict": "proof_graph_bridge",
    "rust_derive_mandatory_assurance": "proof_graph_bridge",
    "rust_verify_fresh_hermetic_proof": "proof_graph_bridge",
    "AssuranceBindingClaim": "proof_graph",
    "G2_13_REQUIRED_STATE_MODEL_FIELD_IDS": "state_model",
    "build_g2_13_state_model": "state_model",
    "independent_derive_expected_runtime_obligation_set": "verifier",
    "ExpectedRuntimeObligation": "runtime_obligation",
    "HazardDisposition": "runtime_obligation",
    "HazardRecord": "runtime_obligation",
    "InvariantCandidateDisposition": "runtime_obligation",
    "InvariantCandidateEntry": "runtime_obligation",
    "InvariantCandidateLedger": "runtime_obligation",
    "InvariantSource": "runtime_obligation",
    "Observer": "runtime_obligation",
    "ObserverFinding": "runtime_obligation",
    "ObserverCoverageDomain": "runtime_obligation",
    "IMPLEMENTED_OBSERVER_COVERAGE_DOMAINS": "runtime_obligation",
    "DEFERRED_OBSERVER_COVERAGE_DOMAINS": "runtime_obligation",
    "RuntimeObligationCandidateDisposition": "runtime_obligation",
    "RuntimeObligationCandidateEntry": "runtime_obligation",
    "RuntimeObligationCandidateLedger": "runtime_obligation",
    "RuntimeObligationClassDeclaration": "runtime_obligation",
    "RuntimeObligationClassKind": "runtime_obligation",
    "RuntimeObligationError": "runtime_obligation",
    "RuntimeObligationRegistry": "runtime_obligation",
    "TerminalDisposition": "runtime_obligation",
    "UnresolvedEffectObservation": "runtime_obligation",
    "check_hazard_disposition_resolves": "runtime_obligation",
    "check_observer_coverage_roster_is_fully_accounted_for": "runtime_obligation",
    "check_observer_has_no_mutation_authority": "runtime_obligation",
    "derive_expected_runtime_obligations": "runtime_obligation",
    "find_missing_runtime_obligations": "runtime_obligation",
    "has_intent_implementation_agreement": "runtime_obligation",
    "RuntimeObligationCliBuildError": "runtime_obligation_bridge",
    "RuntimeObligationCliError": "runtime_obligation_bridge",
    "rust_check_hazard_record": "runtime_obligation_bridge",
    "rust_derive_expected_runtime_obligations": "runtime_obligation_bridge",
    "rust_find_missing_runtime_obligations": "runtime_obligation_bridge",
    "G2_14_REQUIRED_STATE_MODEL_FIELD_IDS": "state_model",
    "build_g2_14_state_model": "state_model",
    "G2_15_REQUIRED_STATE_MODEL_FIELD_IDS": "state_model",
    "build_g2_15_state_model": "state_model",
    "FacilityAdapterBoundary": "facility",
    "FacilityContract": "facility",
    "FacilityError": "facility",
    "FacilityIOClass": "facility",
    "FacilityProperty": "facility",
    "FacilityPropertyQualificationHarness": "facility",
    "LocalSandboxFacility": "facility",
    "PropertyQualificationRecord": "facility",
    "QualificationState": "facility",
    "RealMutatingFacilityAuthorityDisabled": "facility",
    "SandboxScenarioResult": "facility",
    "StaleGenerationRejected": "facility",
    "check_critical_gate": "facility",
    "gen1_check_read_only_facility_admission": "facility",
    "gen1_wrap_read_only_facility_task": "facility",
    "FacilityCliBuildError": "facility_bridge",
    "FacilityCliError": "facility_bridge",
    "rust_can_emit_authoritative_non_occurrence": "facility_bridge",
    "rust_validate_facility_contract": "facility_bridge",
    "AmbientAuthorityInventory": "execution_context",
    "ExecutionAuthorityState": "execution_context",
    "ExecutionContextError": "execution_context",
    "ExecutionContextPrincipal": "execution_context",
    "ExecutionImageLineage": "execution_context",
    "HighRiskUnboundedExecutionRejected": "execution_context",
    "ProbeResult": "execution_context",
    "ProbeStatus": "execution_context",
    "UnadmittedAuthorityReachable": "execution_context",
    "check_high_risk_execution_admission": "execution_context",
    "check_no_unadmitted_authority": "execution_context",
    "classify_execution_authority_state": "execution_context",
    "compute_p0": "execution_context",
    "probe_held_authority": "execution_context",
    "probe_local_positional_authority": "execution_context",
    "probe_network_positional_authority": "execution_context",
    "AutomationCrossCheckResult": "capability_graph",
    "CapabilityCausationGraph": "capability_graph",
    "CapabilityGraphError": "capability_graph",
    "CapabilityNode": "capability_graph",
    "CausalEdge": "capability_graph",
    "ContainingScopeTraversalResult": "capability_graph",
    "EffectivePolicyClaim": "capability_graph",
    "EffectReachResult": "capability_graph",
    "EnumerationState": "capability_graph",
    "HighRiskUnboundedReachRejected": "capability_graph",
    "KnownCausalEdgeClass": "capability_graph",
    "LocalAutomationSubstrate": "capability_graph",
    "NodeKind": "capability_graph",
    "ObservationCover": "capability_graph",
    "ObservationCoverGapDetected": "capability_graph",
    "PositiveControlAttachment": "capability_graph",
    "ReachState": "capability_graph",
    "SubstrateCapabilityGeneration": "capability_graph",
    "SubstrateCapabilityGenerationStale": "capability_graph",
    "check_high_risk_reach_admission": "capability_graph",
    "check_high_risk_reach_state_admission": "capability_graph",
    "check_observation_cover_containment": "capability_graph",
    "check_substrate_capability_generation_current": "capability_graph",
    "classify_reach_state": "capability_graph",
    "compute_effect_reach_star": "capability_graph",
    "cross_check_effective_policy": "capability_graph",
    "query_effective_policy": "capability_graph",
    "traverse_containing_scope": "capability_graph",
    "verify_positive_control_detected": "capability_graph",
    "CapabilityGraphCliBuildError": "capability_graph_bridge",
    "CapabilityGraphCliError": "capability_graph_bridge",
    "rust_check_high_risk_reach_admission": "capability_graph_bridge",
    "rust_check_observation_cover_containment": "capability_graph_bridge",
    "rust_compute_effect_reach_star": "capability_graph_bridge",
    "rust_cross_check_effective_policy": "capability_graph_bridge",
    "AuthorityChain": "root_authority",
    "AuthorityPlane": "root_authority",
    "CausalPreimageResult": "root_authority",
    "CreatedPrincipalAuthorityQuery": "root_authority",
    "LocalPrincipalAuthoritySubstrate": "root_authority",
    "MintableScopeBound": "root_authority",
    "PlaneRole": "root_authority",
    "RootAmendment": "root_authority",
    "RootAuthorityError": "root_authority",
    "check_control_plane_exclusion": "root_authority",
    "check_created_principal_within_mintable_bound": "root_authority",
    "check_successor_bound_non_expansion": "root_authority",
    "compute_causal_preimage_star": "root_authority",
    "query_created_principal_authority": "root_authority",
    "RootAuthorityCliBuildError": "root_authority_bridge",
    "RootAuthorityCliError": "root_authority_bridge",
    "rust_check_control_plane_exclusion": "root_authority_bridge",
    "rust_check_created_principal_within_mintable_bound": "root_authority_bridge",
    "rust_check_successor_bound_non_expansion": "root_authority_bridge",
    "rust_compute_causal_preimage_star": "root_authority_bridge",
    "ALL_MANDATORY_CENSUS_BOUNDARIES": "effect_census",
    "CensusBoundary": "effect_census",
    "EffectCensusEntry": "effect_census",
    "EffectCensusError": "effect_census",
    "EffectCensusRecord": "effect_census",
    "EffectCensusResidueClass": "effect_census",
    "EffectIssuanceBarrier": "effect_census",
    "EffectIssuanceState": "effect_census",
    "ExpectedEffect": "effect_census",
    "LatencyBounds": "effect_census",
    "ObservationCoverStateDigest": "effect_census",
    "ObservedEffect": "effect_census",
    "ObservedLatencies": "effect_census",
    "TerminalEffectSignal": "effect_census",
    "check_effect_integrity": "effect_census",
    "check_latency_bounds": "effect_census",
    "check_mandatory_census_boundaries_covered": "effect_census",
    "check_no_blind_replay": "effect_census",
    "check_no_new_intent_after_closure": "effect_census",
    "check_observation_cover_recheck": "effect_census",
    "classify_effect_census": "effect_census",
    "classify_terminal_signal": "effect_census",
    "close_effect_issuance": "effect_census",
    "compute_observation_cover_state_digest": "effect_census",
    "reopen_effect_issuance": "effect_census",
    "EffectCensusCliBuildError": "effect_census_bridge",
    "EffectCensusCliError": "effect_census_bridge",
    "rust_check_effect_integrity": "effect_census_bridge",
    "rust_check_latency_bounds": "effect_census_bridge",
    "rust_check_mandatory_census_boundaries_covered": "effect_census_bridge",
    "rust_check_no_blind_replay": "effect_census_bridge",
    "rust_check_no_new_intent_after_closure": "effect_census_bridge",
    "rust_check_observation_cover_recheck": "effect_census_bridge",
    "rust_close_effect_issuance": "effect_census_bridge",
    "rust_reopen_effect_issuance": "effect_census_bridge",
    "PROTOCOL_VERSION": "bootstrap_protocol",
    "BootstrapProtocolError": "bootstrap_protocol",
    "EvidencePacketV1": "bootstrap_protocol",
    "FacilityRequestV1": "bootstrap_protocol",
    "FacilityResultV1": "bootstrap_protocol",
    "RuntimeIdentity": "bootstrap_protocol",
    "RuntimeKind": "bootstrap_protocol",
    "TaskPacketV1": "bootstrap_protocol",
    "check_evidence_packet_generation_current": "bootstrap_protocol",
    "check_facility_result_matches_request": "bootstrap_protocol",
    "validate_bootstrap_corpus": "bootstrap_protocol",
    "verify_chronicle_entry_self_digest": "bootstrap_protocol",
    "BootstrapProtocolCliBuildError": "bootstrap_protocol_bridge",
    "BootstrapProtocolCliError": "bootstrap_protocol_bridge",
    "rust_check_evidence_packet_generation_current": "bootstrap_protocol_bridge",
    "rust_check_facility_result_matches_request": "bootstrap_protocol_bridge",
    "rust_validate_bootstrap_corpus": "bootstrap_protocol_bridge",
    "rust_validate_task_packet": "bootstrap_protocol_bridge",
}


def __getattr__(name: str) -> Any:
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = importlib.import_module(f".{module_name}", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_LAZY_EXPORTS))
